---
title: "Webscraping Assignment"
author: "Jordan Daley"
date: "2023-04-05"
output: html_document
---

```{r}
# load twitter library - the rtweet library is recommended now over twitteR
library(rtweet)
# plotting and pipes - tidyverse!
library(ggplot2)
library(dplyr)

```

```{r}
# text mining library
library(tidytext)
# plotting packages
library(igraph)
```

```{r}
# plot the top 15 words -- notice any issues?
climate_tweets_clean %>%
  count(word, sort = TRUE) %>%
  top_n(15) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(x = word, y = n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
      labs(x = "Count",
      y = "Unique words",
      title = "Count of unique words found in tweets")
```

```{r}
library(igraph)
library(ggraph)

# plot climate change word network
# (plotting graph edges is currently broken)
climate_words_counts %>%
        filter(n >= 24) %>%
        graph_from_data_frame() %>%
        ggraph(layout = "fr") +
        geom_edge_link(aes(edge_alpha = n, edge_width = n)) +
        geom_node_point(color = "darkslategray4", size = 3) +
        geom_node_text(aes(label = name), vjust = 1.8, size = 3) +
        labs(title = "Word Network: Tweets using the hashtag - Climate Change",
             subtitle = "Text mining twitter data ",
             x = "", y = "")
```


Question 1: Based on the above data, which movie from which Genre had the longest runtime?

The Action Genre

Question 2: Based on the above data, in the Runtime of 130-160 mins, which genre has the highest votes?

The Biography genre

Based on the above data, across all genres which genre has the highest average gross earnings in runtime 100 to 120.

Animation and Action Genre